# Supabase configuration for the Crypto Confession project

# A string used to distinguish different Supabase projects on the same host
project_id = "crypto-confession"

[api]
# Port to use for the API URL
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage", "auth"]
# Extra schemas to add to the search_path of every request
extra_search_path = ["extensions"]
# The maximum number of rows returns from a view, table, or stored procedure
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322

[studio]
# Port to use for Supabase Studio
port = 54323

[auth]
# The base URL of your website used in email and SMS links
site_url = "http://localhost:3000"

[analytics]
# Enable/Disable the Analytics feature
enabled = false 